spring:
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

  flyway:
    user: ${FLYWAY_USERNAME}
    password: ${FLYWAY_PASSWORD}

  application:
    security:
      jwt:
        expiration: 15m
        refresh-token-expiration: 30d

  jpa:
    open-in-view: false

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}